# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
# ------------------------------------------------
# Answer:4613732


def sum_even_fibonacci(num):
    fibonacci = [1, 2]
    new = fibonacci[-1]

    while new < num:
        new = fibonacci[-1] + fibonacci[-2]
        if (new < num):
            fibonacci.append(new)
    return sum([x for x in fibonacci if x % 2 == 0])


if __name__ == '__main__':
    print(sum_even_fibonacci(4000000))
